services:
  fastapi:
    build:
      context: .
      dockerfile: docker/fastapi.Dockerfile
    image: khstavrev/fastapi-app:latest
    ports:
      - "8000:8000"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://fastapi:8000/docs"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s

  gradio:
    build:
      context: .
      dockerfile: docker/gradio.Dockerfile
    image: khstavrev/gradio-app:latest
    ports:
      - "7860:7860"
    depends_on:
      fastapi:
        condition: service_healthy
    restart: always
