apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.components.fastapi.secret.name }}
  namespace: {{ .Values.namespace }}
type: Opaque

# Must be base64 encoded. Use `echo -n "your_value" | base64` to encode.
data:
  prometheus-user: {{ .Values.fast_api_secret_prometheus_user }}
  prometheus-password: {{ .Values.fast_api_secret_prometheus_password }}
