apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.components.ingress.ingress_name }}
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/affinity-mode: "balanced"
    nginx.ingress.kubernetes.io/session-cookie-name: "INGRESSCOOKIE"
    nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
spec:
  ingressClassName: {{ .Values.components.ingress.ingress_class }}
  rules:
  - host: {{ .Values.components.ingress.ingress_host }}
    http:
      paths:
      - path: {{ .Values.components.ingress.ingress_fastapi_path }}
        pathType: {{ .Values.components.ingress.ingress_fastapi_path_type }}
        backend:
          service:
            name: {{ .Values.components.fastapi.service.service_name }}
            port:
              number: {{ .Values.components.fastapi.service.service_port }}
      - path: {{ .Values.components.ingress.ingress_gradio_path }}
        pathType: {{ .Values.components.ingress.ingress_gradio_path_type }}
        backend:
          service:
            name: {{ .Values.components.gradio.service.service_name }}
            port:
              number: {{ .Values.components.gradio.service.service_port }}
