server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /etc/promtail/positions.yaml

clients:
  - url: ${LOKI_URL}

scrape_configs:
  - job_name: fastapi-logs
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        regex: fastapi
        action: keep
      - source_labels: [__meta_docker_container_log_path]
        target_label: __path__
    pipeline_stages:
      - docker: {}

  - job_name: gradio-logs
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        regex: gradio
        action: keep
      - source_labels: [__meta_docker_container_log_path]
        target_label: __path__
    pipeline_stages:
      - docker: {}
