name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger on pushing to the main branch or merging into it

jobs:
  build:
    runs-on: self-hosted # Running on a self-hosted runner
    
    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v2

      # # Set up Docker Buildx - Commented out because it's not needed anymore on the self-hosted runner
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2
      
      # Log in to Self-Hosted Docker Registry
      - name: Log in to Self-Hosted Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.LOCAL_IMG_REG_IP }}
          username: ${{ secrets.LOCAL_IMG_REG_USER }}
          password: ${{ secrets.LOCAL_IMG_REG_PASS }}

      # Build the Docker image (fastapi and gradio)
      - name: Build Docker Images
        run: |
          REGISTRY_URL=${{ secrets.LOCAL_IMG_REG_IP }} docker compose -f docker-compose.yml build
      
      # Push Docker images to Docker Hub
      - name: Push Docker Images
        run: |
          REGISTRY_URL=${{ secrets.LOCAL_IMG_REG_IP }} docker compose -f docker-compose.yml push

  deploy:
    runs-on: self-hosted # Running on a self-hosted runner
    needs: build  # This job will run after the build job

    steps:
      # Set up SSH key from GitHub secrets
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.P_KEY }}
      
      # SSH into WSL and deploy
      - name: Deploy to WSL
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.USER }}@${{ secrets.IP }} -p ${{ secrets.PORT }} << 'EOF'
            # Log in to self-hosted registry
            echo "${{ secrets.LOCAL_IMG_REG_PASS }}" | docker login ${{ secrets.LOCAL_IMG_REG_IP }} -u ${{ secrets.LOCAL_IMG_REG_USER }} --password-stdin

            # Fetch the docker-compose.yml file
            wget -O /home/${{ secrets.USER }}/deployment/docker-compose.yml \
              https://raw.githubusercontent.com/KristofarStavrev/huggingface_model_deployment/main/docker-compose.yml

            # Pull latest images and restart services
            cd /home/${{ secrets.USER }}/deployment &&
            REGISTRY_URL=${{ secrets.LOCAL_IMG_REG_IP }} docker compose -f docker-compose.yml pull &&
            REGISTRY_URL=${{ secrets.LOCAL_IMG_REG_IP }} docker compose -f docker-compose.yml up -d
          EOF
