name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger on pushing to the main branch or merging into it

jobs:
  build:
    runs-on: self-hosted # Running on a self-hosted runner
    
    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v2

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build the Docker image (fastapi and gradio)
      - name: Build Docker Images
        run: |
          docker compose -f docker-compose.yml build
      
      # Push Docker images to Docker Hub
      - name: Push Docker Images
        run: |
          docker compose -f docker-compose.yml push

      # Upload the docker-compose.yml file as an artifact
      - name: Upload docker-compose.yml as artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-compose
          path: docker-compose.yml

  deploy:
    runs-on: self-hosted # Running on a self-hosted runner
    needs: build  # This job will run after the build job

    steps:
      # Download docker-compose.yml artifact
      - name: Download docker-compose.yml artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-compose

      # Set up SSH key from GitHub secrets
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.P_KEY }}
      
      # SSH into WSL and deploy
      - name: Deploy to WSL
        run: |
          ssh -o StrictHostKeyChecking=no {  secrets.USER  }@{  secrets.IP  } -p {  secrets.PORT  } << 'EOF'
            mkdir -p /home/cicd/deployment && \
            cp /tmp/docker-compose.yml /home/cicd/deployment/ && \
            cd /home/cicd/deployment && \
            docker compose -f docker-compose.yml pull && \
            docker compose -f docker-compose.yml up -d
          EOF
